Doom gruvbox light/fix cursor improve port
hlissner/emacs-doom-themes pull request #525
Opened 2020-10-16 14:56 UTC by drchsl

### Cursor fix and new option
- fixes the cursor being white after startup and black after reloading the theme 
- cursor is now grey, as in the [original gruvbox light](https://github.com/morhetz/gruvbox#light-mode) 
- the black cursor can be brought back by setting `doom-gruvbox-light-darker-cursor` to `t`

### Further port-improvement

- in the [original](https://github.com/morhetz/gruvbox#light-mode) line-numbers have no special background

2020-10-17 00:27 UTC, hlissner requested changes
Could you remove the `doom-gruvbox-light-darker-cursor` option? Unless the implementation is particularly complex, I want to avoid adding options for trivial differences (unless the same/similar option exists upstream). Folks can use `custom-set-faces` otherwise.

2020-10-17 11:21 UTC, drchsl commented
Ah, totally makes sense. Removed it. I only thought "folks might have gotten used to that black cursor" and forgot how easy it is to change that.

2020-10-20 18:42 UTC, hlissner approved these changes

2020-10-20 18:43 UTC, merged

2020-10-20 18:43 UTC, hlissner commented
Thanks!