Improve some Ayu highlight colours in Helm buffers
hlissner/emacs-doom-themes pull request #568
Opened 2021-02-15 03:38 UTC by offbyone

> Please follow these steps before submitting your PR
>
> - [ ] Include before and after screenshots if your change is visual
> - [ ] Please explain what the PR does and why
> - [ ] List and link any packages you are adding support for
> - [ ] Delete this template before submitting
>
> Thank you for contributing to our theme pack!

2021-02-15 03:46 UTC, offbyone commented
### Light
![image](https://user-images.githubusercontent.com/181693/107903174-5a8e7980-6efd-11eb-8120-3ab8a9f363e8.png)

### Mirage
![image](https://user-images.githubusercontent.com/181693/107903169-582c1f80-6efd-11eb-81af-2959757b4486.png)

2021-05-22 03:35 UTC, hlissner requested changes
Could you include "before" screenshots? This PR does not describe how this is an improvement.

2021-05-22 03:35 UTC, hlissner commented on themes/doom-ayu-light-theme.el
> +   (helm-ff-dotted-directory :inherit 'syntax-comment)
What is syntax-comment? It doesn't exist in Emacs 28. Please don't inherit from faces that aren't guaranteed to exist when helm is loaded.

2021-05-22 03:35 UTC, hlissner commented on themes/doom-ayu-mirage-theme.el
> +   (cursor :background "DarkOrange1")
Please use one of our color variables, or use `doom-darken` or `doom-lighten` to adjust them.

2021-05-22 03:35 UTC, hlissner commented on themes/doom-ayu-mirage-theme.el
> +   (helm-ff-dotted-directory :inherit 'syntax-comment)
Again, `syntax-comment`

2021-05-22 03:35 UTC, hlissner commented on themes/doom-ayu-mirage-theme.el
> +   (helm-selection :inherit 'normal :background "DarkOrange1")
Again, use a color variable.

2021-05-22 03:35 UTC, hlissner commented on themes/doom-ayu-light-theme.el
> +   (helm-selection :inherit 'normal :background "#399ee6")
Please don't hardcode colors. Use a color variable and use doom-darken or doom-lighten to adjust them.

2021-09-24 12:23 UTC, closed without merging