Add Monokai Pro Machine, Ristretto, Octagon, Spectrum
hlissner/emacs-doom-themes pull request #601
Opened 2021-05-23 11:11 UTC by minikN

Hello,

I've added the missing filters:
- Octagon
- Ristretto
- Machine
- Spectrum

# Spectrum
![image](https://user-images.githubusercontent.com/1888338/97105259-d0a27280-16b9-11eb-9524-68af7a78183c.png)

# Ristretto
![image](https://user-images.githubusercontent.com/1888338/97105375-8a014800-16ba-11eb-8476-b4fab68515be.png)

# Machine
![image](https://user-images.githubusercontent.com/1888338/97105405-b4eb9c00-16ba-11eb-9753-9b6eecc90718.png)

# Octagon
![image](https://user-images.githubusercontent.com/1888338/97105422-e4020d80-16ba-11eb-935f-27b8a118fbe3.png)

2021-05-23 11:20 UTC, minikN commented
Reference: #532

2021-05-26 19:28 UTC, ema2159 requested changes

2021-05-26 19:28 UTC, ema2159 commented on themes/doom-monokai-octagon-theme.el
> +   (bg-alt     '("#161821" nil       nil            ))
Change bg-alt to #1E1F2B

2021-05-26 19:28 UTC, ema2159 commented on themes/doom-monokai-ristretto-theme.el
> +   (bg-alt     '("#191515" nil       nil            ))
Change bg-alt to #201C1C

2021-05-26 19:28 UTC, ema2159 commented on themes/doom-monokai-machine-theme.el
> +   (bg-alt     '("#161b1e" nil       nil            ))
Change bg-alt to #1E2528

2021-05-28 07:00 UTC, ema2159 approved these changes

2021-05-28 07:01 UTC, ema2159 commented
Excellent job man. Sorry for the delay!

2021-05-28 07:08 UTC, ema2159 commented
One very last thing. If I'm not wrong, if I merge this as it is right now, it will delete the current Monokai pro theme. In order to prevent this I think the only thing to be done is to create again the doom-monokai-pro.el file with the contents of the current implementation. I was going to do so myself but it seems I can't so could you please do this as soon as you have time?

2021-05-28 07:12 UTC, merged